//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBangDiaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.DonVanChuyens = new HashSet<DonVanChuyen>();
        }
    
        public int idDonHang { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public string danhSachSanPham { get; set; }
        public string trangThaiDon { get; set; }
        public Nullable<System.DateTime> ngayDatHang { get; set; }
        public Nullable<decimal> triGiaDon { get; set; }
        public string tenNguoiNhan { get; set; }
    
        public virtual ChiTietDonHang__ ChiTietDonHang__ { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVanChuyen> DonVanChuyens { get; set; }
    }
}
