//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBangDiaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVanChuyen
    {
        public int idDonVanChuyen { get; set; }
        public Nullable<int> idDonHang { get; set; }
        public Nullable<int> idDVVC { get; set; }
        public string hinhThucGiaoHang { get; set; }
        public string trangThaiDonHang { get; set; }
        public Nullable<System.DateTime> ngayGiaoDuKien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual DonViVanChuyen DonViVanChuyen { get; set; }
        public virtual TinhTrangDon TinhTrangDon { get; set; }
    }
}
