//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBangDiaNhac.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    public partial class GioHang
    {
        BangDiaNhacEntities db = new BangDiaNhacEntities();
        public int idSanPham { get; set; }
        public string tenSanPham { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string hinhAnh { get; set; }
        public Nullable<decimal> donGia { get; set; }
        public Nullable<decimal> thanhTien { get { return soLuong * donGia; } }

        public GioHang(int idSanPham)
        {
            this.idSanPham = idSanPham;
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.idSanPham == idSanPham);
            this.tenSanPham = sp.tenSanPham;
                hinhAnh = sp.hinhAnh;
                donGia = decimal.Parse(sp.donGia.ToString());
                soLuong = 1;
            
           
        }
    }
}